// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqWzwywzOrOwDwYg9skwpOSMSpmIeCBHw',
    appId: '1:448655878288:web:dcf7656b6398b4fb675015',
    messagingSenderId: '448655878288',
    projectId: 'laundry-628fd',
    authDomain: 'laundry-628fd.firebaseapp.com',
    storageBucket: 'laundry-628fd.appspot.com',
    measurementId: 'G-PKZYVQ3ZKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgkLzdaP4VHgoHdx8iT3Oj2jSRpYa79Lg',
    appId: '1:448655878288:android:7650239c2f2df582675015',
    messagingSenderId: '448655878288',
    projectId: 'laundry-628fd',
    storageBucket: 'laundry-628fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwk22lpE5hiZw4TLpAF7VYik0CAVudnpM',
    appId: '1:448655878288:ios:75732fd23609a029675015',
    messagingSenderId: '448655878288',
    projectId: 'laundry-628fd',
    storageBucket: 'laundry-628fd.appspot.com',
    iosBundleId: 'com.example.laundry',
  );
}
